import { requireProfile } from "@/lib/auth";
import { Nav } from "@/components/nav";
import { createSupportRequest, updateSupportRequest } from "./actions";

export default async function SupportPage() {
  const { supabase, profile } = await requireProfile();
  const { data: requestsData } = await supabase.from("support_requests").select("*").order("created_at", { ascending: false });
  const { data: loadsData } = await supabase.from("loads").select("id, load_number").order("date_booked", { ascending: false });
  const { data: carriersData } = ["admin","dispatcher"].includes(profile.role) ? await supabase.from("carriers").select("id, company_name").order("company_name") : { data: [] };
  const staff = ["admin","dispatcher"].includes(profile.role);
  return <><Nav profile={profile}/><main className="container"><div className="page-head"><div><div className="eyebrow">Direct operations support</div><h1>Support Requests</h1></div></div><section className="grid two-col"><div><h2>Request history</h2><div className="grid">{(requestsData || []).map(request=><div className="card" key={request.id}><div className="eyebrow">{request.category} · {request.priority}</div><h2>{request.subject}</h2><p>{request.description}</p><span className={`badge ${request.status === "Resolved" ? "success" : request.status === "New" ? "blue" : ""}`}>{request.status}</span>{staff && <form action={updateSupportRequest} className="form section"><input type="hidden" name="id" value={request.id}/><label>Status<select name="status" defaultValue={request.status}>{["New","In Review","Waiting on Carrier","Resolved"].map(v=><option key={v}>{v}</option>)}</select></label><label>Resolution notes<textarea name="resolution_notes" defaultValue={request.resolution_notes || ""}/></label><button className="button small secondary">Update request</button></form>}</div>)}{!(requestsData || []).length && <div className="card muted">No support requests.</div>}</div></div><aside className="card"><h2>Contact FFS</h2><form action={createSupportRequest} className="form">{staff && <label>Carrier<select name="carrier_id" required>{(carriersData || []).map(c=><option value={c.id} key={c.id}>{c.company_name}</option>)}</select></label>}<label>Related load<select name="load_id"><option value="">No specific load</option>{(loadsData || []).map(l=><option value={l.id} key={l.id}>{l.load_number}</option>)}</select></label><label>Category<select name="category">{["Load Question","Document Request","Payment Question","Detention / Layover","Portal Support","General Operations"].map(v=><option key={v}>{v}</option>)}</select></label><label>Priority<select name="priority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label>Subject<input name="subject" required/></label><label>Description<textarea name="description" required/></label><button className="button secondary">Submit to FFS</button></form></aside></section></main></>;
}
