import { requireProfile } from "@/lib/auth";
import { Nav } from "@/components/nav";

export default async function ProfilePage() {
  const { supabase, profile } = await requireProfile();
  const { data: carrier } = profile.carrier_id ? await supabase.from("carriers").select("*").eq("id", profile.carrier_id).single() : { data: null };
  const { data: expiringDocs } = await supabase.from("documents").select("title, document_type, expires_on").not("expires_on", "is", null).lte("expires_on", new Date(Date.now()+30*86400000).toISOString().slice(0,10)).order("expires_on");
  const { data: expiringTrucks } = await supabase.from("trucks").select("unit_number, insurance_expires_on, registration_expires_on").or(`insurance_expires_on.lte.${new Date(Date.now()+30*86400000).toISOString().slice(0,10)},registration_expires_on.lte.${new Date(Date.now()+30*86400000).toISOString().slice(0,10)}`);
  const { data: expiringDrivers } = await supabase.from("drivers").select("full_name, cdl_expires_on, medical_card_expires_on").or(`cdl_expires_on.lte.${new Date(Date.now()+30*86400000).toISOString().slice(0,10)},medical_card_expires_on.lte.${new Date(Date.now()+30*86400000).toISOString().slice(0,10)}`);
  return <><Nav profile={profile}/><main className="container"><div className="page-head"><div><div className="eyebrow">Carrier profile and compliance</div><h1>{carrier?.company_name || profile.full_name}</h1></div></div><section className="grid two-col"><div className="card"><h2>Portal profile</h2><div className="detail-list"><div className="detail-item"><small>Name</small>{profile.full_name}</div><div className="detail-item"><small>Email</small>{profile.email}</div><div className="detail-item"><small>Role</small>{profile.role}</div>{carrier && <><div className="detail-item"><small>Carrier code</small>{carrier.carrier_code}</div><div className="detail-item"><small>MC / DOT</small>{carrier.mc_number || "—"} / {carrier.dot_number || "—"}</div><div className="detail-item"><small>Load fee</small>{(Number(carrier.fee_rate||0)*100).toFixed(2)}%</div><div className="detail-item"><small>Portal plan</small>{carrier.portal_plan}</div><div className="detail-item"><small>Notification email</small>{carrier.notification_email || carrier.email || "Not entered"}</div></>}</div></div><div className="card"><h2>Expiration reminders</h2><div className="grid">{(expiringDocs || []).map((row,index)=><div key={`d${index}`}><strong>{row.document_type}: {row.title}</strong><div className="muted">Expires {row.expires_on}</div></div>)}{(expiringTrucks || []).map((row,index)=><div key={`t${index}`}><strong>Truck {row.unit_number}</strong><div className="muted">Insurance {row.insurance_expires_on || "—"} · Registration {row.registration_expires_on || "—"}</div></div>)}{(expiringDrivers || []).map((row,index)=><div key={`r${index}`}><strong>{row.full_name}</strong><div className="muted">CDL {row.cdl_expires_on || "—"} · Medical {row.medical_card_expires_on || "—"}</div></div>)}{!(expiringDocs || []).length && !(expiringTrucks || []).length && !(expiringDrivers || []).length && <div className="muted">No expirations within 30 days.</div>}</div></div></section></main></>;
}
