import { requireProfile } from "@/lib/auth";
import { Nav } from "@/components/nav";
import { addTruck, addDriver } from "./actions";

export default async function FleetPage() {
  const { supabase, profile } = await requireProfile();
  const { data: trucksData } = await supabase.from("trucks").select("*").order("unit_number");
  const { data: driversData } = await supabase.from("drivers").select("*, trucks(unit_number)").order("full_name");
  const { data: carriersData } = profile.role === "admin" || profile.role === "dispatcher" ? await supabase.from("carriers").select("id, company_name, carrier_code").order("company_name") : { data: [] };
  const canManage = ["admin", "dispatcher", "carrier_owner"].includes(profile.role);
  return <><Nav profile={profile}/><main className="container"><div className="page-head"><div><div className="eyebrow">Fleet management</div><h1>Trucks & Drivers</h1></div></div>
    <section className="grid two-col"><div><h2>Trucks</h2><div className="grid">{(trucksData || []).map(truck=><div className="card" key={truck.id}><div className="eyebrow">Unit {truck.unit_number}</div><h2>{truck.year || ""} {truck.make || ""} {truck.model || ""}</h2><p><strong>Equipment:</strong> {truck.equipment_type}</p><p><strong>Capacity:</strong> {truck.capacity_lbs ? `${Number(truck.capacity_lbs).toLocaleString()} lbs` : "Not entered"}</p><p><strong>Insurance expires:</strong> {truck.insurance_expires_on || "Not entered"}</p><p><strong>Registration expires:</strong> {truck.registration_expires_on || "Not entered"}</p><span className="badge success">{truck.status}</span></div>)}{!(trucksData || []).length && <div className="card muted">No trucks added.</div>}</div></div><div><h2>Drivers</h2><div className="grid">{(driversData || []).map(driver=><div className="card" key={driver.id}><div className="eyebrow">Driver</div><h2>{driver.full_name}</h2><p>{driver.phone || "No phone"}<br/>{driver.email || "No portal email"}</p><p><strong>Assigned unit:</strong> {driver.trucks?.unit_number || "Unassigned"}</p><p><strong>CDL expires:</strong> {driver.cdl_expires_on || "Not entered"}</p><p><strong>Medical card expires:</strong> {driver.medical_card_expires_on || "Not entered"}</p><span className="badge success">{driver.status}</span></div>)}{!(driversData || []).length && <div className="card muted">No drivers added.</div>}</div></div></section>
    {canManage && <section className="grid two-col section"><div className="card"><h2>Add truck</h2><form action={addTruck} className="form">{profile.carrier_id ? <input type="hidden" name="carrier_id" value={profile.carrier_id}/> : <label>Carrier<select name="carrier_id" required>{(carriersData || []).map(c=><option value={c.id} key={c.id}>{c.company_name} ({c.carrier_code})</option>)}</select></label>}<div className="form-grid"><label>Unit number<input name="unit_number" required/></label><label>Equipment type<input name="equipment_type" placeholder="26 ft box truck" required/></label><label>Year<input type="number" name="year"/></label><label>Make<input name="make"/></label><label>Model<input name="model"/></label><label>VIN last 6<input name="vin_last6" maxLength={6}/></label><label>Capacity lbs<input type="number" name="capacity_lbs"/></label><label>Plate<input name="plate_number"/></label><label>Insurance expiration<input type="date" name="insurance_expires_on"/></label><label>Registration expiration<input type="date" name="registration_expires_on"/></label></div><button className="button secondary">Add truck</button></form></div>{["admin","dispatcher"].includes(profile.role) && <div className="card"><h2>Add driver and optional login</h2><form action={addDriver} className="form"><label>Carrier<select name="carrier_id" required>{(carriersData || []).map(c=><option value={c.id} key={c.id}>{c.company_name}</option>)}</select></label><label>Full name<input name="full_name" required/></label><div className="form-grid"><label>Email<input type="email" name="email"/></label><label>Temporary password<input type="password" name="temporary_password" minLength={8}/></label><label>Phone<input name="phone"/></label><label>Assigned truck<select name="assigned_truck_id"><option value="">Unassigned</option>{(trucksData || []).map(t=><option value={t.id} key={t.id}>{t.unit_number}</option>)}</select></label><label>CDL number<input name="cdl_number"/></label><label>CDL expiration<input type="date" name="cdl_expires_on"/></label><label>Medical card expiration<input type="date" name="medical_card_expires_on"/></label><label>Emergency contact<input name="emergency_contact"/></label></div><p className="muted">Email and temporary password are optional. Enter both to create a driver portal login.</p><button className="button secondary">Add driver</button></form></div>}</section>}
  </main></>;
}
