import { requireProfile } from "@/lib/auth";
import { Nav } from "@/components/nav";
import { addFuelEntry, addMileageEntry } from "./actions";
import { money } from "@/lib/utils";

export default async function FuelMileagePage() {
  const { supabase, profile } = await requireProfile();
  const { data: fuelData } = await supabase.from("fuel_entries").select("*").order("entry_date", { ascending: false });
  const { data: mileageData } = await supabase.from("mileage_entries").select("*").order("entry_date", { ascending: false });
  const { data: loadsData } = await supabase.from("loads").select("id, load_number").order("date_booked", { ascending: false });
  const { data: trucksData } = await supabase.from("trucks").select("id, unit_number").order("unit_number");
  const { data: driversData } = await supabase.from("drivers").select("id, full_name").order("full_name");
  const { data: carriersData } = ["admin","dispatcher"].includes(profile.role) ? await supabase.from("carriers").select("id, company_name").order("company_name") : { data: [] };
  const fuel = fuelData || []; const mileage = mileageData || [];
  const fuelTotal = fuel.reduce((sum,row)=>sum+Number(row.amount||0),0); const gallons=fuel.reduce((sum,row)=>sum+Number(row.gallons||0),0); const loaded=mileage.reduce((sum,row)=>sum+Number(row.loaded_miles||0),0); const deadhead=mileage.reduce((sum,row)=>sum+Number(row.deadhead_miles||0),0);
  const carrierSelect = ["admin","dispatcher"].includes(profile.role) ? <label>Carrier<select name="carrier_id" required>{(carriersData || []).map(c=><option value={c.id} key={c.id}>{c.company_name}</option>)}</select></label> : null;
  return <><Nav profile={profile}/><main className="container"><div className="page-head"><div><div className="eyebrow">Operating cost visibility</div><h1>Fuel & Mileage</h1></div></div><section className="grid kpis"><div className="card kpi"><div className="kpi-label">Fuel spend</div><div className="kpi-value">{money.format(fuelTotal)}</div></div><div className="card kpi"><div className="kpi-label">Gallons</div><div className="kpi-value">{gallons.toFixed(1)}</div></div><div className="card kpi"><div className="kpi-label">Loaded miles</div><div className="kpi-value">{loaded.toLocaleString()}</div></div><div className="card kpi"><div className="kpi-label">Deadhead miles</div><div className="kpi-value">{deadhead.toLocaleString()}</div></div><div className="card kpi"><div className="kpi-label">Fuel cost / mile</div><div className="kpi-value">{money.format(loaded+deadhead ? fuelTotal/(loaded+deadhead) : 0)}</div></div><div className="card kpi"><div className="kpi-label">Deadhead ratio</div><div className="kpi-value">{loaded+deadhead ? ((deadhead/(loaded+deadhead))*100).toFixed(1) : "0.0"}%</div></div></section>
    <section className="grid two-col section"><div className="card"><h2>Add fuel entry</h2><form action={addFuelEntry} className="form">{carrierSelect}<div className="form-grid"><label>Date<input type="date" name="entry_date" required/></label><label>Vendor<input name="vendor"/></label><label>City<input name="city"/></label><label>State<input name="state"/></label><label>Gallons<input type="number" step="0.001" name="gallons" required/></label><label>Price / gallon<input type="number" step="0.001" name="price_per_gallon"/></label><label>Total amount<input type="number" step="0.01" name="amount" required/></label><label>Odometer<input type="number" step="0.1" name="odometer"/></label><label>Truck<select name="truck_id"><option value="">Unassigned</option>{(trucksData || []).map(t=><option value={t.id} key={t.id}>{t.unit_number}</option>)}</select></label><label>Driver<select name="driver_id"><option value="">Unassigned</option>{(driversData || []).map(d=><option value={d.id} key={d.id}>{d.full_name}</option>)}</select></label><label>Load<select name="load_id"><option value="">No load</option>{(loadsData || []).map(l=><option value={l.id} key={l.id}>{l.load_number}</option>)}</select></label></div><label>Notes<textarea name="notes"/></label><button className="button secondary">Add fuel record</button></form></div><div className="card"><h2>Add mileage entry</h2><form action={addMileageEntry} className="form">{carrierSelect}<div className="form-grid"><label>Date<input type="date" name="entry_date" required/></label><label>Start<input name="start_location"/></label><label>End<input name="end_location"/></label><label>Loaded miles<input type="number" step="0.1" name="loaded_miles"/></label><label>Deadhead miles<input type="number" step="0.1" name="deadhead_miles"/></label><label>Personal miles<input type="number" step="0.1" name="personal_miles"/></label><label>Truck<select name="truck_id"><option value="">Unassigned</option>{(trucksData || []).map(t=><option value={t.id} key={t.id}>{t.unit_number}</option>)}</select></label><label>Driver<select name="driver_id"><option value="">Unassigned</option>{(driversData || []).map(d=><option value={d.id} key={d.id}>{d.full_name}</option>)}</select></label><label>Load<select name="load_id"><option value="">No load</option>{(loadsData || []).map(l=><option value={l.id} key={l.id}>{l.load_number}</option>)}</select></label></div><label>Notes<textarea name="notes"/></label><button className="button secondary">Add mileage record</button></form></div></section>
    <section className="grid two-col section"><div><h2>Recent fuel</h2><div className="table-wrap"><table><thead><tr><th>Date</th><th>Vendor</th><th>Gallons</th><th>Amount</th></tr></thead><tbody>{fuel.slice(0,12).map(row=><tr key={row.id}><td>{row.entry_date}</td><td>{row.vendor || `${row.city || ""}, ${row.state || ""}`}</td><td>{Number(row.gallons||0).toFixed(2)}</td><td>{money.format(Number(row.amount||0))}</td></tr>)}</tbody></table></div></div><div><h2>Recent mileage</h2><div className="table-wrap"><table><thead><tr><th>Date</th><th>Route</th><th>Loaded</th><th>Deadhead</th></tr></thead><tbody>{mileage.slice(0,12).map(row=><tr key={row.id}><td>{row.entry_date}</td><td>{row.start_location || ""} → {row.end_location || ""}</td><td>{Number(row.loaded_miles||0)}</td><td>{Number(row.deadhead_miles||0)}</td></tr>)}</tbody></table></div></div></section>
  </main></>;
}
